name=PosixAsyncTCP
version=0.1.0
author=Will Miles
maintainer=Will Miles
sentence=Asynchronous TCP library for HOST/POSIX targets (Linux/macOS), compatible with AsyncTCP API.
paragraph=Asynchronous TCP library for HOST/POSIX targets (Linux/macOS), intended as a compatibility layer for libraries such as ESPAsyncWebServer.
category=Communication
url=https://github.com/MitchBradley/PosixAsyncTCP
architectures=*
repository=https://github.com/MitchBradley/PosixAsyncTCP
license=LGPL-3.0
includes=AsyncTCP.h
